// // This file is automatically generated. Do not edit it directly.
// import { createClient } from '@supabase/supabase-js';
// import type { Database } from './types';

// const SUPABASE_URL = "https://rjoirkhkrulahqbotmeq.supabase.co";
// const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqb2lya2hrcnVsYWhxYm90bWVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxOTg2MzMsImV4cCI6MjA2OTc3NDYzM30.iPl-hQmxNjQD4iITg_Lx03GoqTjtSm0blzGo47fMMX4";

// // Import the supabase client like this:
// // import { supabase } from "@/integrations/supabase/client";

// export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
//   auth: {
//     storage: localStorage,
//     persistSession: true,
//     autoRefreshToken: true,
//   }
// });
import { createClient } from '@supabase/supabase-js'

const supabaseUrl = 'https://rjoirkhkrulahqbotmeq.supabase.co'
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqb2lya2hrcnVsYWhxYm90bWVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxOTg2MzMsImV4cCI6MjA2OTc3NDYzM30.iPl-hQmxNjQD4iITg_Lx03GoqTjtSm0blzGo47fMMX4'
export const supabase = createClient(supabaseUrl, supabaseKey)